[package]
name = "torrent-rs"
version = "0.1.0"
authors = ["sepiropht <sergembotta@mailoo.org>"]
edition = "2018"

[dependencies]
hyper = "0.5"
rand = "0.3"
rust-crypto = "0.2"
simple_bencode = "0.1.4"

[dependencies.url]
git = "https://github.com/servo/rust-url"

