[package]
name = "torrent-rs"
version = "0.1.0"
authors = ["sepiropht <sergembotta@mailoo.org>"]
edition = "2018"

[dependencies]
bencode = "0.1.16"
bendy = "0.3.3"
dns-lookup = "1.0.8"
url = "2.3.1"

