[package]
name = "torrent-rs"
version = "0.1.0"
authors = ["sepiropht <sergembotta@mailoo.org>"]
edition = "2018"

[dependencies]
rust-crypto = "0.2"
[dependencies.bencode]

git = "https://github.com/arjantop/rust-bencode.git"
